### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sheitandard** [aminallam/karect#2]
Hi

I am trying Karect and I got this error when i am trying to correct the reads:
./karect -correct -threads=12 -matchtype=hamming -celltype=haploid -inputfile=./index-18_S18_all_R1_001_egal.fastq -inputfile=./index-18_S18_all_R2_001_egal.fastq
Error Correction Started
Estimated Coverage     = 838.295878
Global Num Reads       = 40572076
Global Num Bases       = 6078085735
Global Num Kmers       = 5753509127
Global Max Read Len    = 150
Global Avg Read Len    = 149.809582
Min Overlap            = 35
Min Overlap Percentage = 0.200000
Max Overlap Error Rate = 0.250000
Truncate Factor        = 0.000000
Min Straight Edge Val  = 100.000000
Min Straight Edge Per  = 1.000000
Min Read Weight        = 0.000000
Max Mul Len Matches    = 13422818
Max Kmer Slots         = 100000
Use Qual               = 1
Match Type             = Hamming Distance
Kmer Size              = 12
Max Kmer Errors        = 2
Kmer With Errors Size  = 12
Read Index Bits        = 40
Num Threads            = 12
Memory Budget          = 10995116277760[10240g]
File Block Size        = 10485760[10m]
Cache Block Size       = 134217728[128m]
Max Reads Per Step     = 1000
Max Part Res           = 150
Main CorrectErrors StartFile=0
Total Reads Size = 12237315623
Building Index [0 - 12196743546]
Erreur de segmentation (core dumped)

Do you know what could be the problem?

**Comment by aminallam** [comment]
This issue happens when karect requires more memory than than the amount of available RAM on your machine. Please run karect again with the option -memory=d where d is the amount of RAM on your machine in gigabytes. Also, I recommend to use the machine with largest RAM available in your lab for this dataset.

**Comment by sheitandard** [comment]
Thanks

I have tried -memory=d and it has worked without problem
