### ISSUE TITLE
Clarification of CLI memory flag description

### ISSUE THREAD

**Issue by LeeBergstrand** [aminallam/karect#3]
Hi!

If you call `karect -correct` you get a help menu with a list of optional flags. Specifically, i'm interested in the memory flag.

``` shell
  "-memory=d":         Specify an upper bound on the memory that can be used in gigabytes [Default=10240.0].
```

Does this mean that the default upper bound is 10240.0 Gigabytes (i.e. 10.24 Terabytes)?

Also in what format do I specify the my own maximum memory parameters?

Like this `-memory=64` for 64 Gigabytes?

Thanks,

Cheers,

Lee

**Comment by aminallam** [comment]
Yes, the default main memory upper bound is 10 Terabytes. Setting -memory=64 will set the upper bound to 64 Gigabytes (the format you specified is correct).

**Comment by LeeBergstrand** [comment]
Sounds great. Thanks for the quick response!
