### ISSUE TITLE
Test data error?

### ISSUE THREAD

**Issue by colindaven** [aminallam/karect#4]
Hi,

just tried this on the test data.

It seems to have failed without an error, or are the files karect_frag_1.fastq and 2.fastq the output files?

The log was fine

Min Read Weight        = 0.000000
Max Mul Len Matches    = 19801980
Max Kmer Slots         = 100000
Use Qual               = 1
Match Type             = Hamming Distance
Kmer Size              = 9
Max Kmer Errors        = 2
Kmer With Errors Size  = 9
Read Index Bits        = 32
Num Threads            = 24
Memory Budget          = 10995116277760[10240g]
File Block Size        = 10485760[10m]
Cache Block Size       = 134217728[128m]
Max Reads Per Step     = 1000
Max Part Res           = 30
Main CorrectErrors StartFile=0
Total Reads Size = 263997217
Building Index [0 - 262703112]
Building Index Finished
Each following dot indicates that 1% of the required processing at current stage has been finished:
...................................................................................................
Error Correction Finished

but it seems the output files are exactly the same size as the input files - is this to be expected ?

thanks

-rw-rw-r-- 1 rcug rcug      1403 Jul 18 08:18 error.log
-rw-rw-r-- 1 rcug rcug 146798341 Apr 14  2011 frag_1.fastq
-rw-rw-r-- 1 rcug rcug 146798341 Apr 14  2011 frag_2.fastq
-rw-rw-r-- 1 rcug rcug  68386818 Apr 14  2011 frag_2.fastq.gz
-rw-rw-r-- 1 rcug rcug 262703112 Jul 17 17:02 input_file.txt
-rw-rw-r-- 1 rcug rcug 146798341 Jul 17 17:04 karect_frag_1.fastq
-rw-rw-r-- 1 rcug rcug 146798341 Jul 17 17:16 karect_frag_2.fastq
-rw-rw-r-- 1 rcug rcug         0 Jul 17 17:16 res_graph_a.txt
-rw-rw-r-- 1 rcug rcug         0 Jul 17 17:16 res_graph_b.txt
-rw-rw-r-- 1 rcug rcug         0 Jul 17 17:02 temp_res_frag_1.fastq
-rw-rw-r-- 1 rcug rcug         0 Jul 17 17:02 temp_res_frag_2.fastq

**Comment by aminallam** [comment]
The files karect_frag_1.fastq and karect_frag_2.fastq are the output files. Their contents should differ from the input files. They have the same size as input files as expected because, when using hamming distance, only substitutions of incorrect bases are allowed.

**Comment by colindaven** [comment]
Ok, thanks!
- The four files with size 0 lead me to believe that an error has occurred
Colin
